#!/bin/bash
export GULPPATH=$HOME/GULP-4.2.0/Src
gfortran topol_SiGeO.f90 -o topol_SiGeO
ls *.gin > list
while read line ; do
 file=$line
 name=$(echo $line | sed 's/\.gin//g')
 cp $file tmp.gin
 #cat $line oxygen.bottom > tmp.gin
 sed -i 's/ Ge/Ge /g'      tmp.gin
 sed -i 's/ Si/Si /g'      tmp.gin
 echo ===========
 ./topol_SiGeO < tmp.gin
 gin=${name}.mod.gin
 gout=${name}.gout
 gres=${name}.res
 mv out.gin $gin
 rm tmp.gin
 sed -i "s/output cif out/output cif ${name}/g"          $gin
 sed -i "s/dump every 1     out/dump every 1  ${name}/g" $gin
 sed -i 's/maxcyc opt     5000/maxcyc opt 1000/g'        $gin
 mpirun --np 30 $GULPPATH/gulp < $gin > $gout
 sed "s/opti conv qok/opti conp qok/g" $gres > $gin
 sed -i 's/maxcyc opt     5000/maxcyc opt 1000/g' $gin
 mpirun --np 30 $GULPPATH/gulp < $gin > $gout
 sed -i "/stepmx opt     0.01/d" $gres > $gin
 sed -i 's/maxcyc opt     5000/maxcyc opt 1000/g' $gin
 mpirun --np 30 $GULPPATH/gulp < $gin > $gout
 mv $gres $gin
 sed -i 's/maxcyc opt     5000/maxcyc opt 1000/g' $gin
 sed -i "s/opti conp qok/opti conp qok rfo/g"     $gin 
 $GULPPATH/gulp < $gin > $gout
 sleep 0.1
 rm gulptmp_*
done < list
rm topol_SiGeO list
exit 0
