#!/bin/bash
#rm ener vol  a b c alpha beta gamma
ls *.gout | while read line ; do
 grep 'Final energy =' $line | awk '{print $4}' >> ener 
 for cell in a b c alpha beta gamma ; do
  grep -A10 'Final cell parameters and derivatives :' $line | grep " $cell " | awk '{print $2}' >> $cell
 done
 grep 'Primitive cell volume =' $line | awk '{print $5}' >> vol 
done
paste OUTSOD ener vol a b c alpha beta gamma
rm ener vol  a b c alpha beta gamma
