#!/bin/bash
gfortran topol_SiGeO.f90 -o topol_SiGeO
ls *.gin | while read line ; do
 echo $line
 echo ===========
 ./topol_SiGeO < $line
 gin=${line}.gin
 gout="$(echo $line | sed "s/\.gin//g").gout"
 gres="out.res"
 mv out.gin $gin
 mpirun --np 16 gulp < $gin > $gout
 sed "s/opti conv qok/opti conp qok/g" $gres > $gin
 mpirun --np 16 gulp < $gin > $gout
 sed -i "s/stepmx opt     0.01/stepmx opt     0.1/g" $gres > $gin
 mpirun --np 16 gulp < $gin > $gout
 mv $gres $gin
 gulp < $gin > $gout
 mv out.cif ${line}.cif
 mv $gres ${gin}.res
done
exit 0
